export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';

export const LOG_IN_FACEBOOK_REQUEST = 'LOG_IN_FACEBOOK_REQUEST';
export const LOG_IN_FACEBOOK_SUCCESS = 'LOG_IN_FACEBOOK_SUCCESS';
export const LOG_IN_FACEBOOK_FAILURE = 'LOG_IN_FACEBOOK_FAILURE';
 
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';

export const APP_OPEN = 'APP_OPEN';
